# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1649526420dca3a8e2d9d62ea34fa14c550e46f475e49c40adae53f8fd5b456adcb208df69473302fc71f04f724fc2a683c52fe387582f692fe4cdcf0cd56708

test:
  secret_key_base: 776018bf731cf75fcc19c488ee07a241fec73dafa97bfeed6e1694417010bb82f5f239f6078a6910b5d9357c583d40cf9f9ad7cdb812eb82b85b93867e63bb12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
